//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Service.Control.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Service.Control.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ntlmdomain:{0}.
        /// </summary>
        internal static string FormatAuthority {
            get {
                return ResourceManager.GetString("FormatAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\{0}\root\MSCluster.
        /// </summary>
        internal static string FormatClusterManagementScope {
            get {
                return ResourceManager.GetString("FormatClusterManagementScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSCluster_Resource.Name=&apos;{0}&apos;.
        /// </summary>
        internal static string FormatClusterResourceManagementPath {
            get {
                return ResourceManager.GetString("FormatClusterResourceManagementPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///{1}.
        /// </summary>
        internal static string FormatLogError {
            get {
                return ResourceManager.GetString("FormatLogError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\\\{0}\\root\\CIMV2.
        /// </summary>
        internal static string FormatServiceManagementScope {
            get {
                return ResourceManager.GetString("FormatServiceManagementScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error altering service state {0}
        ///Error:{1}.
        /// </summary>
        internal static string FormatServiceStateErrorMessage {
            get {
                return ResourceManager.GetString("FormatServiceStateErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service {0} is :{1}.
        /// </summary>
        internal static string FormatServiceStateMessage {
            get {
                return ResourceManager.GetString("FormatServiceStateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        internal static string LocalCluster {
            get {
                return ResourceManager.GetString("LocalCluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to root\MSCluster.
        /// </summary>
        internal static string LocalScope {
            get {
                return ResourceManager.GetString("LocalScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to root\CIMV2.
        /// </summary>
        internal static string LocalServiceScope {
            get {
                return ResourceManager.GetString("LocalServiceScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log4net.config.
        /// </summary>
        internal static string LogfileConfigurationName {
            get {
                return ResourceManager.GetString("LogfileConfigurationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find log file.
        /// </summary>
        internal static string LogFileNotFoundMessage {
            get {
                return ResourceManager.GetString("LogFileNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NameProperty {
            get {
                return ResourceManager.GetString("NameProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer or service name specified.
        /// </summary>
        internal static string NoComputerOrServiceMessage {
            get {
                return ResourceManager.GetString("NoComputerOrServiceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TakeOffline.
        /// </summary>
        internal static string OfflineFunctionName {
            get {
                return ResourceManager.GetString("OfflineFunctionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BringOnline.
        /// </summary>
        internal static string OnlineFunctionName {
            get {
                return ResourceManager.GetString("OnlineFunctionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeOut.
        /// </summary>
        internal static string ParameterTimeoutName {
            get {
                return ResourceManager.GetString("ParameterTimeoutName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication specified but domain, user, or password is not provided.
        /// </summary>
        internal static string ServiceAuthError {
            get {
                return ResourceManager.GetString("ServiceAuthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StopService.
        /// </summary>
        internal static string ServiceOfflineFunctionName {
            get {
                return ResourceManager.GetString("ServiceOfflineFunctionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartService.
        /// </summary>
        internal static string ServiceOnlineFunctionName {
            get {
                return ResourceManager.GetString("ServiceOnlineFunctionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error pausing service.
        /// </summary>
        internal static string ServicePauseError {
            get {
                return ResourceManager.GetString("ServicePauseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error resuming service.
        /// </summary>
        internal static string ServiceResumeError {
            get {
                return ResourceManager.GetString("ServiceResumeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error starting service.
        /// </summary>
        internal static string ServiceStartError {
            get {
                return ResourceManager.GetString("ServiceStartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error stopping service.
        /// </summary>
        internal static string ServiceStopError {
            get {
                return ResourceManager.GetString("ServiceStopError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string StateProperty {
            get {
                return ResourceManager.GetString("StateProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM MSCluster_Resource.
        /// </summary>
        internal static string WmiClusterResourceQuery {
            get {
                return ResourceManager.GetString("WmiClusterResourceQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win32_Service.Name=&apos;{0}&apos;.
        /// </summary>
        internal static string WmiServiceResourceQuery {
            get {
                return ResourceManager.GetString("WmiServiceResourceQuery", resourceCulture);
            }
        }
    }
}
